mysite/myapp/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth.views import LoginView, LogoutView

from . import views

urlpatterns = [
    path('', views.home, name = 'Home'),
    path('articles/', views.ArticlesList.as_view(), name = 'Articles'),
    path('articles/<slug:slug>/', views.ArticleDetail, name='article_details'),
    path('pictures/', views.PicturesList.as_view(), name = 'Pictures'),
    path('pictures/<slug:slug>/', views.PicturesDetail, name='picture_details'),
    path('resume/', views.resume, name = 'Resume'),
    path('chat/', views.chat, name = 'Chat'),
    path('chat/<str:room_name>/', views.room, name='room'),
    path('register/', views.register, name = 'Register'),
    path('login/', LoginView.as_view(template_name = 'myapp/login.html'), name = 'Login'),
    path('logout/', LogoutView.as_view(template_name = 'myapp/logout.html'), name = 'Logout'),
]

mysite/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

import myapp

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/myapp/models.py
import os
from django.db import models
from django.conf import settings
from django.contrib.auth.models import User
# Create your models here.

class Articles(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    content = models.TextField()
    datePosted = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-datePosted']
        
    def __str__(self):
        return self.title


class Comment(models.Model):
    comment = models.CharField(max_length=240)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Articles, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

def images_path():
    return os.path.join(settings.LOCAL_FILE_DIR, 'pictures')

class Pictures(models.Model):
    title = models.CharField(max_length=100)
    slug = models.SlugField(max_length=200, unique=True)
    description = models.CharField(max_length=100)
    datePosted = models.DateTimeField(auto_now_add=True)
    dateTaken = models.DateField()
    picture = models.ImageField(null=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-datePosted']

    def __str__(self):
        return self.description

class PicComment(models.Model):
    comment = models.CharField(max_length=240)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.ForeignKey(Pictures, on_delete=models.CASCADE)

    def __str__(self):
        return self.comment

mysite/myapp/forms.py
from django import forms
from .models import Comment, Articles, Pictures, PicComment

#class CommentForm(forms.ModelForm):
    #class Meta:
        #model = Comment
        #fields = ('author','comment')

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('comment' ,)

class PicCommentForm(forms.ModelForm):
    class Meta:
        model = PicComment
        fields = ('comment' ,)

mysite/myapp/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Articles, Comment, Pictures, PicComment
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from .forms import CommentForm, PicCommentForm
from django.views import generic


# Create your views here.
def home(request):
    return render(request, 'myapp/home.html')

class ArticlesList(generic.ListView):
    queryset = Articles.objects.filter().order_by('-datePosted')
    template_name = 'myapp/articles.html'

class ArticleDetail(generic.DetailView):
    model = Articles
    template_name ='myapp/article_details.html'

class PicturesList(generic.ListView):
    queryset = Pictures.objects.filter().order_by('-datePosted')
    template_name = 'myapp/pictures.html'

class PicturesDetail(generic.DetailView):
    model = Articles
    template_name ='myapp/picture_details.html'

# def pictures(request):
#     context = {
#         'pictures': Pictures.objects.all(),
#     }
#     return render(request, 'myapp/pictures.html', context)

def resume(request):
    return render(request, 'myapp/resume.html')

def chat(request):
    return render(request, 'myapp/chat.html')

def room(request, room_name):
    return render(request, 'myapp/room.html', {
        'room_name': room_name
    })

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            return redirect('Home')
    else:
        form = UserCreationForm()
    return render(request, 'myapp/register.html', {'form': form})

def ArticleDetail(request,slug):
    template_name = 'myapp/article_details.html'
    article = get_object_or_404(Articles, slug=slug)
    comments = Comment.objects.filter(content=article)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        # if request.user.is_authenticated:
        #     return redirect('Login')
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.author = request.user
            new_comment.content = article
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    
    return render(request, template_name, {'article': article, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form}) 

def PicturesDetail(request,slug):
    template_name = 'myapp/picture_details.html'
    picture = get_object_or_404(Pictures, slug=slug)
    comments = PicComment.objects.filter(content=picture)
    new_comment = None
    # Comment posted
    if request.method == 'POST':
        # if request.user.is_authenticated:
        #     return redirect('Login')
        comment_form = PicCommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.author = request.user
            new_comment.content = picture
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = PicCommentForm()
    
    return render(request, template_name, {'picture': picture, 'comments': comments, 'new_comment': new_comment, 'comment_form': comment_form})    

mysite/myapp/templates/myapp/addComment.html
{% extends "myapp/base.html" %}
{% block content%}
    <h1> Add comment</h1>
    <form action="/comment_form/{{ art_id }}/" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button type="button" class="btn btn-primary">Submit</button>
    </form>
{% endblock content %}

mysite/myapp/templates/myapp/article_details.html
{% extends "myapp/base.html" %}
{% block content %}
    <article class="media content-section">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2" >{{ article.author }}</a>
                <small class="text-muted">{{ article.datePosted|date:"F d, Y" }}</small>
            </div>
            <h2><a class="article-title" href="#">{{ article.title }}</a></h2>
            <p class="article-content">{{ article.content }}</p>
        </div>
    </article>
    <div class="mb-4">
        <hr class="solid">
        <h6 class ="text">Comment Section</h6>
        <hr class="solid">
    </div>

    {% for comment in comments %}
        <p class="comment"> via: {{ comment.author }}</p>
        <p class="comment">{{ comment.comment }}</p>
        <hr>
        {% empty %}
        <p style>There is no comments</p>
    {% endfor %}
    {% if request.user.is_authenticated %}
        <div class="content-section">
            <form method='POST'>
                {% csrf_token %}
                {{ comment_form.as_p }}
                <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
            </form>
        </div>
    {% endif %}

    {% if not request.user.is_authenticated %}
        <h3> Please log in to comment </h3>
        <br>
    {% endif %}
{% endblock content %}

mysite/myapp/templates/myapp/articles.html
{% extends "myapp/base.html" %}
{% block content %}
    {% for article in articles_list %}
        <article class="media content-section">
            <div class="media-body">
                <div class="article-metadata">
                    <a class="mr-2" >{{ article.author }}</a>
                    <small class="text-muted">{{ article.datePosted|date:"F d, Y" }}</small>
                </div>
                <h2><a class="article-title" href="{% url 'article_details' article.slug %}">{{ article.title }}</a></h2>
                <p class="article-content">{{ article.content }}</p>
                </div>

            </div>
        </article>
    {% endfor %}
{% endblock content %}

mysite/myapp/templates/myapp/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
     <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
     <link rel="stylesheet" type="text/css" href="{% static 'css/app.css'%}">
     <link href='https://fonts.googleapis.com/css?family=Roboto' rel='stylesheet'>
     <title> </title>

  </head>
  <body>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark">
          <a href="{% url 'Home' %}" class="navbar-brand">Miguel's Website</a>
          <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
              <span class="navbar-toggler-icon"></span>
          </button>
      
          <div class="collapse navbar-collapse" id="navbarCollapse">
              <div class="navbar-nav">
                  <a href="{% url 'Home' %}" class="nav-item nav-link">Home</a>
                  <a href="{% url 'Articles' %}" class="nav-item nav-link">Articles</a>
                  <a href="{% url 'Pictures' %}" class="nav-item nav-link">Pictures</a>
                  <a href="{% url 'Resume' %}" class="nav-item nav-link">Resume</a>
                  <a href="/chat/lobby" class="nav-item nav-link">Chat</a>
              </div>
              <div class="navbar-nav ml-auto">
                  {% if user.is_authenticated %}
                    <a class="nav-item nav-link">Welcome {{user.username}}</a>
                  {% else %}
                    <a class="nav-item nav-link">Welcome Guest</a>
                  {% endif %}
                  {% if user.is_authenticated %}
                  <a href="{% url 'Logout' %}" class="nav-item nav-link">Logout</a>
                  {% else %}
                  <a href="{% url 'Login' %}" class="nav-item nav-link">Login</a>
                  <a href="{% url 'Register' %}" class="nav-item nav-link">Register</a>
                  {% endif %}
              </div>
          </div>
      </nav>
      <div class = "container">
        {% block content%} 
        {% endblock %}
      </div>
      <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

mysite/myapp/templates/myapp/chat.html
{% extends "myapp/base.html" %}
{% block content %}
    What chat room would you like to enter?<br>
    <input id="room-name-input" type="text" size="100"><br>
    <input id="room-name-submit" type="button" value="Enter">

    <script>
        document.querySelector('#room-name-input').focus();
        document.querySelector('#room-name-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#room-name-submit').click();
            }
        };

        document.querySelector('#room-name-submit').onclick = function(e) {
            var roomName = document.querySelector('#room-name-input').value;
            window.location.pathname = '/chat/' + roomName + '/';
        };
    </script>
{% endblock content %}

mysite/myapp/templates/myapp/home.html
{% extends "myapp/base.html" %}
{% block content %}
    <br>
    <img src="/static/profile.jpg" alt="Profile photo" class="profile"/>

    <div class = "row">
        <div class="col">
            <h2>About me</h2>
            <hr width = 50%>
            <p> I am currently a Junior at California State University, Chico.</p>
            <p> I'm on track to graduate in the Spring of 2021</p>
        </div>
    </div>
        <div class = "row">
            <div class = "col-md-4">
                <div class="card card-body">
                    <br>
                    <i class='fa fa-user' style='font-size:35px'></i>
                    <hr>
                    <h3>Info</h3>
                    <h3 class="info"> Born and raised in Chico </h3>
                    <h3 class="info"> 1st generation College student </h3>
                    <h3 class="info"> Computer Science Major </h3>
                    <h3 class="info"> Currently working as a Sterile Processing Tech </h3>
                </div>
            </div>
            <div class = "col-md-4">
                <div class="card card-body">
                    <br>
                    <i class="fa fa-puzzle-piece" style='font-size:35px'></i>
                    <hr>
                    <h3>Hobbies</h3>
                    <h3 class="info"> Programming (of course) </h3>
                    <h3 class="info"> Playing soccer </h3>
                    <h3 class="info"> Playing video games </h3>
                    <h3 class="info"> Going on runs in the park </h3>
                    <h3 class="info"> Yoyoing </h3>
                </div>
            </div>
            <div class = "col-md-4">
                <div class="card card-body">
                    <br>
                    <i class="fa fa-question-circle" style='font-size:35px'></i>
                    <hr>
                    <h3>Questions?</h3>
                    <p>You can find my resume <a href="{% url 'Resume' %}">here</a>. 
                    If you want to contact me here is my contact information</p>
                    <h3 class="info"> Email: Mrosales1095@gmail.com </h3>


                </div>
            </div>
        </div>
    
    <ul class="horizontal">
        <li class="horizontal"><a href="https://github.com/bofomiso"><i class="fa fa-github fa-2x" style="color:black;"></i></a></li>
        <li class="horizontal"><a href="https://www.linkedin.com/in/miguel-rosales-134b031a6/"><i class="fa fa-linkedin fa-2x" style="color:black;"></i></a></li>
        <li class="horizontal"><a href="https://www.facebook.com/miguel.rosales.5473"><i class="fa fa-facebook fa-2x" style="color:black;"></i></a></li> 
    </ul>
{% endblock content%}

mysite/myapp/templates/myapp/login.html
{% extends "myapp/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                {{ form.as_p }}
            </fieldset>
            <div class = form-group>
                <button class="btn btn-outline-info" type ="submit">Submit</button>
            </div>
        </form>
    </div>
{% endblock content %}

mysite/myapp/templates/myapp/logout.html
{% extends "myapp/base.html" %}

{% block content %}
<h2>You just logged out </h2>
{% endblock content %}

mysite/myapp/templates/myapp/picture_details.html
{% extends "myapp/base.html" %}
{% block content %}

<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted"> Date created: {{ picture.datePosted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ picture.description }}</a></h2>
        <div class="row">
            <div class="col-md-6">
                <img src="{{ picture.picture.url }}" class="img-thumbnail" height=400 width = 400/>
            </div>
            <div class="col-md-6">
                <h3 class="desc"> Picture was taken on: {{ picture.dateTaken }} </h3>
            </div>
        </div>
    </div>
</article>
<div class="mb-4">
    <hr class="solid">
    <h6 class ="text">Comment Section</h6>
    <hr class="solid">
</div>

{% for comment in comments %}
    <p class="comment"> via: {{ comment.author }}</p>
    <p class="comment">{{ comment.comment }}</p>
    <hr>
    {% empty %}
    <p style>There is no comments</p>
{% endfor %}
{% if request.user.is_authenticated %}
    <div class="content-section">
        <form method='POST'>
            {% csrf_token %}
            {{ comment_form.as_p }}
            <button type="submit" class="btn btn-primary  btn-lg">Submit</button>
        </form>
    </div>
{% endif %}

{% if not request.user.is_authenticated %}
    <h3> Please log in to comment </h3>
    <br>
{% endif %}

{% endblock content %}

mysite/myapp/templates/myapp/pictures.html
{% extends "myapp/base.html" %}
{% block content %}
{% for picture in pictures %}
<article class="media content-section">
    <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted"> Date created: {{ picture.datePosted|date:"F d, Y" }}</small>
        </div>
        <h2><a class="article-title" href="#">{{ picture.description }}</a></h2>
        <div class="row">
            <div class="col-md-6">
                <img src="{{ picture.picture }}" class="img-thumbnail" height=400 width = 400/>
            </div>
            <div class="col-md-6">
                <h3 class="desc"> Picture was taken on: {{ picture.dateTaken }} </h3>
            </div>
        </div>
    </div>
</article>
{% endfor %}
{% endblock content %}

mysite/myapp/templates/myapp/register.html
{% extends "myapp/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class = "form-group">
                {{ form.as_p }}
            </fieldset>
            <div class = form-group>
                <button class="btn btn-outline-info" type ="submit">Submit</button>
            </div>
        </form>
    </div>
  
{% endblock content %}

mysite/myapp/templates/myapp/resume.html
{% extends "myapp/base.html" %}
{% block content %}
    <br>
    <img src="/static/resume.jpg" alt="Resume" class="resume"/>
{% endblock content %}

mysite/myapp/templates/myapp/room.html
{% extends "myapp/base.html" %}
{% block content %}
    <br>
    <h3> Chat </h3>
    
    <textarea id="chat-log" cols="100" rows="20" class="form-control" readonly=True></textarea><br>
    <input id="chat-message-input" type="text" size="100" class="form-control"><br>
    <input id="chat-message-submit" type="button" value="Send" class="form-control">
    {{ room_name|json_script:"room-name" }}
    <script>
        const roomName = JSON.parse(document.getElementById('room-name').textContent);

        const chatSocket = new WebSocket(
            'ws://'
            + window.location.host
            + '/ws/chat/'
            + roomName
            + '/'
        );

        chatSocket.onmessage = function(e) {
            const data = JSON.parse(e.data);
            document.querySelector('#chat-log').value += (data.message + '\n');
        };

        chatSocket.onclose = function(e) {
            console.error('Chat socket closed unexpectedly');
        };

        document.querySelector('#chat-message-input').focus();
        document.querySelector('#chat-message-input').onkeyup = function(e) {
            if (e.keyCode === 13) {  // enter, return
                document.querySelector('#chat-message-submit').click();
            }
        };

        document.querySelector('#chat-message-submit').onclick = function(e) {
            const messageInputDom = document.querySelector('#chat-message-input');
            const message = messageInputDom.value;
            chatSocket.send(JSON.stringify({
                'message': message
            }));
            messageInputDom.value = '';
        };
    </script>
{% endblock content %}